<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.0
 */

/**
 * Database `test`
 */

/* `test`.`countries` */
$countries = array(
  array('id' => '1','name' => 'Afghanistan','slug' => 'afghanistan','sortname' => 'AF','status' => '1'),
  array('id' => '2','name' => 'Albania','slug' => 'albania','sortname' => 'AL','status' => '1'),
  array('id' => '3','name' => 'Algeria','slug' => 'algeria','sortname' => 'DZ','status' => '1'),
  array('id' => '4','name' => 'American Samoa','slug' => 'american-samoa','sortname' => 'AS','status' => '1'),
  array('id' => '5','name' => 'Andorra','slug' => 'andorra','sortname' => 'AD','status' => '1'),
  array('id' => '6','name' => 'Angola','slug' => 'angola','sortname' => 'AO','status' => '1'),
  array('id' => '7','name' => 'Anguilla','slug' => 'anguilla','sortname' => 'AI','status' => '1'),
  array('id' => '8','name' => 'Antarctica','slug' => 'antarctica','sortname' => 'AQ','status' => '1'),
  array('id' => '9','name' => 'Antigua And Barbuda','slug' => 'antigua-and-barbuda','sortname' => 'AG','status' => '1'),
  array('id' => '10','name' => 'Argentina','slug' => 'argentina','sortname' => 'AR','status' => '1'),
  array('id' => '11','name' => 'Armenia','slug' => 'armenia','sortname' => 'AM','status' => '1'),
  array('id' => '12','name' => 'Aruba','slug' => 'aruba','sortname' => 'AW','status' => '1'),
  array('id' => '13','name' => 'Australia','slug' => 'australia','sortname' => 'AU','status' => '1'),
  array('id' => '14','name' => 'Austria','slug' => 'austria','sortname' => 'AT','status' => '1'),
  array('id' => '15','name' => 'Azerbaijan','slug' => 'azerbaijan','sortname' => 'AZ','status' => '1'),
  array('id' => '17','name' => 'Bahrain','slug' => 'bahrain','sortname' => 'BH','status' => '1'),
  array('id' => '18','name' => 'Bangladesh','slug' => 'bangladesh','sortname' => 'BD','status' => '1'),
  array('id' => '19','name' => 'Barbados','slug' => 'barbados','sortname' => 'BB','status' => '1'),
  array('id' => '20','name' => 'Belarus','slug' => 'belarus','sortname' => 'BY','status' => '1'),
  array('id' => '21','name' => 'Belgium','slug' => 'belgium','sortname' => 'BE','status' => '1'),
  array('id' => '22','name' => 'Belize','slug' => 'belize','sortname' => 'BZ','status' => '1'),
  array('id' => '23','name' => 'Benin','slug' => 'benin','sortname' => 'BJ','status' => '1'),
  array('id' => '24','name' => 'Bermuda','slug' => 'bermuda','sortname' => 'BM','status' => '1'),
  array('id' => '25','name' => 'Bhutan','slug' => 'bhutan','sortname' => 'BT','status' => '1'),
  array('id' => '26','name' => 'Bolivia','slug' => 'bolivia','sortname' => 'BO','status' => '1'),
  array('id' => '27','name' => 'Bosnia and Herzegovina','slug' => 'bosnia-and-herzegovina','sortname' => 'BA','status' => '1'),
  array('id' => '28','name' => 'Botswana','slug' => 'botswana','sortname' => 'BW','status' => '1'),
  array('id' => '29','name' => 'Bouvet Island','slug' => 'bouvet-island','sortname' => 'BV','status' => '1'),
  array('id' => '30','name' => 'Brazil','slug' => 'brazil','sortname' => 'BR','status' => '1'),
  array('id' => '31','name' => 'British Indian Ocean Territory','slug' => 'british-indian-ocean-territory','sortname' => 'IO','status' => '1'),
  array('id' => '32','name' => 'Brunei','slug' => 'brunei','sortname' => 'BN','status' => '1'),
  array('id' => '33','name' => 'Bulgaria','slug' => 'bulgaria','sortname' => 'BG','status' => '1'),
  array('id' => '34','name' => 'Burkina Faso','slug' => 'burkina-faso','sortname' => 'BF','status' => '1'),
  array('id' => '35','name' => 'Burundi','slug' => 'burundi','sortname' => 'BI','status' => '1'),
  array('id' => '36','name' => 'Cambodia','slug' => 'cambodia','sortname' => 'KH','status' => '1'),
  array('id' => '37','name' => 'Cameroon','slug' => 'cameroon','sortname' => 'CM','status' => '1'),
  array('id' => '38','name' => 'Canada','slug' => 'canada','sortname' => 'CA','status' => '1'),
  array('id' => '39','name' => 'Cape Verde','slug' => 'cape-verde','sortname' => 'CV','status' => '1'),
  array('id' => '40','name' => 'Cayman Islands','slug' => 'cayman-islands','sortname' => 'KY','status' => '1'),
  array('id' => '41','name' => 'Central African Republic','slug' => 'central-african-republic','sortname' => 'CF','status' => '1'),
  array('id' => '42','name' => 'Chad','slug' => 'chad','sortname' => 'TD','status' => '1'),
  array('id' => '43','name' => 'Chile','slug' => 'chile','sortname' => 'CL','status' => '1'),
  array('id' => '44','name' => 'China','slug' => 'china','sortname' => 'CN','status' => '1'),
  array('id' => '45','name' => 'Christmas Island','slug' => 'christmas-island','sortname' => 'CX','status' => '1'),
  array('id' => '46','name' => 'Cocos (Keeling) Islands','slug' => 'cocos-keeling-islands','sortname' => 'CC','status' => '1'),
  array('id' => '47','name' => 'Colombia','slug' => 'colombia','sortname' => 'CO','status' => '1'),
  array('id' => '48','name' => 'Comoros','slug' => 'comoros','sortname' => 'KM','status' => '1'),
  array('id' => '51','name' => 'Cook Islands','slug' => 'cook-islands','sortname' => 'CK','status' => '1'),
  array('id' => '52','name' => 'Costa Rica','slug' => 'costa-rica','sortname' => 'CR','status' => '1'),
  array('id' => '55','name' => 'Cuba','slug' => 'cuba','sortname' => 'CU','status' => '1'),
  array('id' => '56','name' => 'Cyprus','slug' => 'cyprus','sortname' => 'CY','status' => '1'),
  array('id' => '57','name' => 'Czech Republic','slug' => 'czech-republic','sortname' => 'CZ','status' => '1'),
  array('id' => '58','name' => 'Denmark','slug' => 'denmark','sortname' => 'DK','status' => '1'),
  array('id' => '59','name' => 'Djibouti','slug' => 'djibouti','sortname' => 'DJ','status' => '1'),
  array('id' => '60','name' => 'Dominica','slug' => 'dominica','sortname' => 'DM','status' => '1'),
  array('id' => '61','name' => 'Dominican Republic','slug' => 'dominican-republic','sortname' => 'DO','status' => '1'),
  array('id' => '63','name' => 'Ecuador','slug' => 'ecuador','sortname' => 'EC','status' => '1'),
  array('id' => '64','name' => 'Egypt','slug' => 'egypt','sortname' => 'EG','status' => '1'),
  array('id' => '65','name' => 'El Salvador','slug' => 'el-salvador','sortname' => 'SV','status' => '1'),
  array('id' => '66','name' => 'Equatorial Guinea','slug' => 'equatorial-guinea','sortname' => 'GQ','status' => '1'),
  array('id' => '67','name' => 'Eritrea','slug' => 'eritrea','sortname' => 'ER','status' => '1'),
  array('id' => '68','name' => 'Estonia','slug' => 'estonia','sortname' => 'EE','status' => '1'),
  array('id' => '69','name' => 'Ethiopia','slug' => 'ethiopia','sortname' => 'ET','status' => '1'),
  array('id' => '71','name' => 'Falkland Islands','slug' => 'falkland-islands','sortname' => 'FK','status' => '1'),
  array('id' => '72','name' => 'Faroe Islands','slug' => 'faroe-islands','sortname' => 'FO','status' => '1'),
  array('id' => '74','name' => 'Finland','slug' => 'finland','sortname' => 'FI','status' => '1'),
  array('id' => '75','name' => 'France','slug' => 'france','sortname' => 'FR','status' => '1'),
  array('id' => '76','name' => 'French Guiana','slug' => 'french-guiana','sortname' => 'GF','status' => '1'),
  array('id' => '77','name' => 'French Polynesia','slug' => 'french-polynesia','sortname' => 'PF','status' => '1'),
  array('id' => '79','name' => 'Gabon','slug' => 'gabon','sortname' => 'GA','status' => '1'),
  array('id' => '81','name' => 'Georgia','slug' => 'georgia','sortname' => 'GE','status' => '1'),
  array('id' => '82','name' => 'Germany','slug' => 'germany','sortname' => 'DE','status' => '1'),
  array('id' => '83','name' => 'Ghana','slug' => 'ghana','sortname' => 'GH','status' => '1'),
  array('id' => '84','name' => 'Gibraltar','slug' => 'gibraltar','sortname' => 'GI','status' => '1'),
  array('id' => '85','name' => 'Greece','slug' => 'greece','sortname' => 'GR','status' => '1'),
  array('id' => '86','name' => 'Greenland','slug' => 'greenland','sortname' => 'GL','status' => '1'),
  array('id' => '87','name' => 'Grenada','slug' => 'grenada','sortname' => 'GD','status' => '1'),
  array('id' => '88','name' => 'Guadeloupe','slug' => 'guadeloupe','sortname' => 'GP','status' => '1'),
  array('id' => '89','name' => 'Guam','slug' => 'guam','sortname' => 'GU','status' => '1'),
  array('id' => '90','name' => 'Guatemala','slug' => 'guatemala','sortname' => 'GT','status' => '1'),
  array('id' => '92','name' => 'Guinea','slug' => 'guinea','sortname' => 'GN','status' => '1'),
  array('id' => '93','name' => 'Guinea-Bissau','slug' => 'guinea-bissau','sortname' => 'GW','status' => '1'),
  array('id' => '94','name' => 'Guyana','slug' => 'guyana','sortname' => 'GY','status' => '1'),
  array('id' => '95','name' => 'Haiti','slug' => 'haiti','sortname' => 'HT','status' => '1'),
  array('id' => '97','name' => 'Honduras','slug' => 'honduras','sortname' => 'HN','status' => '1'),
  array('id' => '99','name' => 'Hungary','slug' => 'hungary','sortname' => 'HU','status' => '1'),
  array('id' => '100','name' => 'Iceland','slug' => 'iceland','sortname' => 'IS','status' => '1'),
  array('id' => '101','name' => 'India','slug' => 'india','sortname' => 'IN','status' => '1'),
  array('id' => '102','name' => 'Indonesia','slug' => 'indonesia','sortname' => 'ID','status' => '1'),
  array('id' => '103','name' => 'Iran','slug' => 'iran','sortname' => 'IR','status' => '1'),
  array('id' => '104','name' => 'Iraq','slug' => 'iraq','sortname' => 'IQ','status' => '1'),
  array('id' => '105','name' => 'Ireland','slug' => 'ireland','sortname' => 'IE','status' => '1'),
  array('id' => '106','name' => 'Israel','slug' => 'israel','sortname' => 'IL','status' => '1'),
  array('id' => '107','name' => 'Italy','slug' => 'italy','sortname' => 'IT','status' => '1'),
  array('id' => '108','name' => 'Jamaica','slug' => 'jamaica','sortname' => 'JM','status' => '1'),
  array('id' => '109','name' => 'Japan','slug' => 'japan','sortname' => 'JP','status' => '1'),
  array('id' => '110','name' => 'Jersey','slug' => 'jersey','sortname' => 'JE','status' => '1'),
  array('id' => '111','name' => 'Jordan','slug' => 'jordan','sortname' => 'JO','status' => '1'),
  array('id' => '112','name' => 'Kazakhstan','slug' => 'kazakhstan','sortname' => 'KZ','status' => '1'),
  array('id' => '113','name' => 'Kenya','slug' => 'kenya','sortname' => 'KE','status' => '1'),
  array('id' => '114','name' => 'Kiribati','slug' => 'kiribati','sortname' => 'KI','status' => '1'),
  array('id' => '117','name' => 'Kuwait','slug' => 'kuwait','sortname' => 'KW','status' => '1'),
  array('id' => '118','name' => 'Kyrgyzstan','slug' => 'kyrgyzstan','sortname' => 'KG','status' => '1'),
  array('id' => '119','name' => 'Laos','slug' => 'laos','sortname' => 'LA','status' => '1'),
  array('id' => '120','name' => 'Latvia','slug' => 'latvia','sortname' => 'LV','status' => '1'),
  array('id' => '121','name' => 'Lebanon','slug' => 'lebanon','sortname' => 'LB','status' => '1'),
  array('id' => '122','name' => 'Lesotho','slug' => 'lesotho','sortname' => 'LS','status' => '1'),
  array('id' => '123','name' => 'Liberia','slug' => 'liberia','sortname' => 'LR','status' => '1'),
  array('id' => '124','name' => 'Libya','slug' => 'libya','sortname' => 'LY','status' => '1'),
  array('id' => '125','name' => 'Liechtenstein','slug' => 'liechtenstein','sortname' => 'LI','status' => '1'),
  array('id' => '126','name' => 'Lithuania','slug' => 'lithuania','sortname' => 'LT','status' => '1'),
  array('id' => '127','name' => 'Luxembourg','slug' => 'luxembourg','sortname' => 'LU','status' => '1'),
  array('id' => '129','name' => 'Macedonia','slug' => 'macedonia','sortname' => 'MK','status' => '1'),
  array('id' => '130','name' => 'Madagascar','slug' => 'madagascar','sortname' => 'MG','status' => '1'),
  array('id' => '131','name' => 'Malawi','slug' => 'malawi','sortname' => 'MW','status' => '1'),
  array('id' => '132','name' => 'Malaysia','slug' => 'malaysia','sortname' => 'MY','status' => '1'),
  array('id' => '133','name' => 'Maldives','slug' => 'maldives','sortname' => 'MV','status' => '1'),
  array('id' => '134','name' => 'Mali','slug' => 'mali','sortname' => 'ML','status' => '1'),
  array('id' => '135','name' => 'Malta','slug' => 'malta','sortname' => 'MT','status' => '1'),
  array('id' => '137','name' => 'Marshall Islands','slug' => 'marshall-islands','sortname' => 'MH','status' => '1'),
  array('id' => '138','name' => 'Martinique','slug' => 'martinique','sortname' => 'MQ','status' => '1'),
  array('id' => '139','name' => 'Mauritania','slug' => 'mauritania','sortname' => 'MR','status' => '1'),
  array('id' => '140','name' => 'Mauritius','slug' => 'mauritius','sortname' => 'MU','status' => '1'),
  array('id' => '141','name' => 'Mayotte','slug' => 'mayotte','sortname' => 'YT','status' => '1'),
  array('id' => '142','name' => 'Mexico','slug' => 'mexico','sortname' => 'MX','status' => '1'),
  array('id' => '143','name' => 'Micronesia','slug' => 'micronesia','sortname' => 'FM','status' => '1'),
  array('id' => '144','name' => 'Moldova','slug' => 'moldova','sortname' => 'MD','status' => '1'),
  array('id' => '145','name' => 'Monaco','slug' => 'monaco','sortname' => 'MC','status' => '1'),
  array('id' => '146','name' => 'Mongolia','slug' => 'mongolia','sortname' => 'MN','status' => '1'),
  array('id' => '147','name' => 'Montserrat','slug' => 'montserrat','sortname' => 'MS','status' => '1'),
  array('id' => '148','name' => 'Morocco','slug' => 'morocco','sortname' => 'MA','status' => '1'),
  array('id' => '149','name' => 'Mozambique','slug' => 'mozambique','sortname' => 'MZ','status' => '1'),
  array('id' => '150','name' => 'Myanmar','slug' => 'myanmar','sortname' => 'MM','status' => '1'),
  array('id' => '151','name' => 'Namibia','slug' => 'namibia','sortname' => 'NA','status' => '1'),
  array('id' => '152','name' => 'Nauru','slug' => 'nauru','sortname' => 'NR','status' => '1'),
  array('id' => '153','name' => 'Nepal','slug' => 'nepal','sortname' => 'NP','status' => '1'),
  array('id' => '156','name' => 'New Caledonia','slug' => 'new-caledonia','sortname' => 'NC','status' => '1'),
  array('id' => '157','name' => 'New Zealand','slug' => 'new-zealand','sortname' => 'NZ','status' => '1'),
  array('id' => '158','name' => 'Nicaragua','slug' => 'nicaragua','sortname' => 'NI','status' => '1'),
  array('id' => '159','name' => 'Niger','slug' => 'niger','sortname' => 'NE','status' => '1'),
  array('id' => '160','name' => 'Nigeria','slug' => 'nigeria','sortname' => 'NG','status' => '1'),
  array('id' => '161','name' => 'Niue','slug' => 'niue','sortname' => 'NU','status' => '1'),
  array('id' => '162','name' => 'Norfolk Island','slug' => 'norfolk-island','sortname' => 'NF','status' => '1'),
  array('id' => '163','name' => 'Northern Mariana Islands','slug' => 'northern-mariana-islands','sortname' => 'MP','status' => '1'),
  array('id' => '164','name' => 'Norway','slug' => 'norway','sortname' => 'NO','status' => '1'),
  array('id' => '165','name' => 'Oman','slug' => 'oman','sortname' => 'OM','status' => '1'),
  array('id' => '166','name' => 'Pakistan','slug' => 'pakistan','sortname' => 'PK','status' => '1'),
  array('id' => '167','name' => 'Palau','slug' => 'palau','sortname' => 'PW','status' => '1'),
  array('id' => '169','name' => 'Panama','slug' => 'panama','sortname' => 'PA','status' => '1'),
  array('id' => '170','name' => 'Papua new Guinea','slug' => 'papua-new-guinea','sortname' => 'PG','status' => '1'),
  array('id' => '171','name' => 'Paraguay','slug' => 'paraguay','sortname' => 'PY','status' => '1'),
  array('id' => '172','name' => 'Peru','slug' => 'peru','sortname' => 'PE','status' => '1'),
  array('id' => '173','name' => 'Philippines','slug' => 'philippines','sortname' => 'PH','status' => '1'),
  array('id' => '175','name' => 'Poland','slug' => 'poland','sortname' => 'PL','status' => '1'),
  array('id' => '176','name' => 'Portugal','slug' => 'portugal','sortname' => 'PT','status' => '1'),
  array('id' => '177','name' => 'Puerto Rico','slug' => 'puerto-rico','sortname' => 'PR','status' => '1'),
  array('id' => '178','name' => 'Qatar','slug' => 'qatar','sortname' => 'QA','status' => '1'),
  array('id' => '179','name' => 'Reunion','slug' => 'reunion','sortname' => 'RE','status' => '1'),
  array('id' => '180','name' => 'Romania','slug' => 'romania','sortname' => 'RO','status' => '1'),
  array('id' => '181','name' => 'Russia','slug' => 'russia','sortname' => 'RU','status' => '1'),
  array('id' => '182','name' => 'Rwanda','slug' => 'rwanda','sortname' => 'RW','status' => '1'),
  array('id' => '184','name' => 'Saint Kitts And Nevis','slug' => 'saint-kitts-and-nevis','sortname' => 'KN','status' => '1'),
  array('id' => '185','name' => 'Saint Lucia','slug' => 'saint-lucia','sortname' => 'LC','status' => '1'),
  array('id' => '186','name' => 'Saint Pierre and Miquelon','slug' => 'saint-pierre-and-miquelon','sortname' => 'PM','status' => '1'),
  array('id' => '187','name' => 'Saint Vincent And The Grenadines','slug' => 'saint-vincent-and-the-grenadines','sortname' => 'VC','status' => '1'),
  array('id' => '188','name' => 'Samoa','slug' => 'samoa','sortname' => 'WS','status' => '1'),
  array('id' => '189','name' => 'San Marino','slug' => 'san-marino','sortname' => 'SM','status' => '1'),
  array('id' => '190','name' => 'Sao Tome and Principe','slug' => 'sao-tome-and-principe','sortname' => 'ST','status' => '1'),
  array('id' => '191','name' => 'Saudi Arabia','slug' => 'saudi-arabia','sortname' => 'SA','status' => '1'),
  array('id' => '192','name' => 'Senegal','slug' => 'senegal','sortname' => 'SN','status' => '1'),
  array('id' => '193','name' => 'Serbia','slug' => 'serbia','sortname' => 'RS','status' => '1'),
  array('id' => '194','name' => 'Seychelles','slug' => 'seychelles','sortname' => 'SC','status' => '1'),
  array('id' => '195','name' => 'Sierra Leone','slug' => 'sierra-leone','sortname' => 'SL','status' => '1'),
  array('id' => '196','name' => 'Singapore','slug' => 'singapore','sortname' => 'SG','status' => '1'),
  array('id' => '197','name' => 'Slovakia','slug' => 'slovakia','sortname' => 'SK','status' => '1'),
  array('id' => '198','name' => 'Slovenia','slug' => 'slovenia','sortname' => 'SI','status' => '1'),
  array('id' => '200','name' => 'Solomon Islands','slug' => 'solomon-islands','sortname' => 'SB','status' => '1'),
  array('id' => '201','name' => 'Somalia','slug' => 'somalia','sortname' => 'SO','status' => '1'),
  array('id' => '202','name' => 'South Africa','slug' => 'south-africa','sortname' => 'ZA','status' => '1'),
  array('id' => '203','name' => 'South Georgia','slug' => 'south-georgia','sortname' => 'GS','status' => '1'),
  array('id' => '204','name' => 'South Sudan','slug' => 'south-sudan','sortname' => 'SS','status' => '1'),
  array('id' => '205','name' => 'Spain','slug' => 'spain','sortname' => 'ES','status' => '1'),
  array('id' => '206','name' => 'Sri Lanka','slug' => 'sri-lanka','sortname' => 'LK','status' => '1'),
  array('id' => '207','name' => 'Sudan','slug' => 'sudan','sortname' => 'SD','status' => '1'),
  array('id' => '208','name' => 'Suriname','slug' => 'suriname','sortname' => 'SR','status' => '1'),
  array('id' => '210','name' => 'Swaziland','slug' => 'swaziland','sortname' => 'SZ','status' => '1'),
  array('id' => '211','name' => 'Sweden','slug' => 'sweden','sortname' => 'SE','status' => '1'),
  array('id' => '212','name' => 'Switzerland','slug' => 'switzerland','sortname' => 'CH','status' => '1'),
  array('id' => '213','name' => 'Syria','slug' => 'syria','sortname' => 'SY','status' => '1'),
  array('id' => '214','name' => 'Taiwan','slug' => 'taiwan','sortname' => 'TW','status' => '1'),
  array('id' => '215','name' => 'Tajikistan','slug' => 'tajikistan','sortname' => 'TJ','status' => '1'),
  array('id' => '216','name' => 'Tanzania','slug' => 'tanzania','sortname' => 'TZ','status' => '1'),
  array('id' => '217','name' => 'Thailand','slug' => 'thailand','sortname' => 'TH','status' => '1'),
  array('id' => '218','name' => 'Togo','slug' => 'togo','sortname' => 'TG','status' => '1'),
  array('id' => '219','name' => 'Tokelau','slug' => 'tokelau','sortname' => 'TK','status' => '1'),
  array('id' => '220','name' => 'Tonga','slug' => 'tonga','sortname' => 'TO','status' => '1'),
  array('id' => '221','name' => 'Trinidad And Tobago','slug' => 'trinidad-and-tobago','sortname' => 'TT','status' => '1'),
  array('id' => '222','name' => 'Tunisia','slug' => 'tunisia','sortname' => 'TN','status' => '1'),
  array('id' => '223','name' => 'Turkey','slug' => 'turkey','sortname' => 'TR','status' => '1'),
  array('id' => '224','name' => 'Turkmenistan','slug' => 'turkmenistan','sortname' => 'TM','status' => '1'),
  array('id' => '225','name' => 'Turks And Caicos Islands','slug' => 'turks-and-caicos-islands','sortname' => 'TC','status' => '1'),
  array('id' => '226','name' => 'Tuvalu','slug' => 'tuvalu','sortname' => 'TV','status' => '1'),
  array('id' => '227','name' => 'Uganda','slug' => 'uganda','sortname' => 'UG','status' => '1'),
  array('id' => '228','name' => 'Ukraine','slug' => 'ukraine','sortname' => 'UA','status' => '1'),
  array('id' => '229','name' => 'United Arab Emirates','slug' => 'united-arab-emirates','sortname' => 'AE','status' => '1'),
  array('id' => '230','name' => 'United Kingdom','slug' => 'united-kingdom','sortname' => 'GB','status' => '1'),
  array('id' => '231','name' => 'United States','slug' => 'united-states','sortname' => 'US','status' => '1'),
  array('id' => '232','name' => 'United States Minor Outlying Islands','slug' => 'united-states-minor-outlying-islands','sortname' => 'UM','status' => '1'),
  array('id' => '233','name' => 'Uruguay','slug' => 'uruguay','sortname' => 'UY','status' => '1'),
  array('id' => '234','name' => 'Uzbekistan','slug' => 'uzbekistan','sortname' => 'UZ','status' => '1'),
  array('id' => '235','name' => 'Vanuatu','slug' => 'vanuatu','sortname' => 'VU','status' => '1'),
  array('id' => '237','name' => 'Venezuela','slug' => 'venezuela','sortname' => 'VE','status' => '1'),
  array('id' => '238','name' => 'Vietnam','slug' => 'vietnam','sortname' => 'VN','status' => '1'),
  array('id' => '242','name' => 'Western Sahara','slug' => 'western-sahara','sortname' => 'EH','status' => '1'),
  array('id' => '243','name' => 'Yemen','slug' => 'yemen','sortname' => 'YE','status' => '1'),
  array('id' => '245','name' => 'Zambia','slug' => 'zambia','sortname' => 'ZM','status' => '1'),
  array('id' => '246','name' => 'Zimbabwe','slug' => 'zimbabwe','sortname' => 'ZW','status' => '1')
);

foreach($countries as $country) {
    Country::create([
        'id' => $country['id'],
        'name' => $country['name'],
        'slug' => $country['slug'],
        'sortname' => $country['sortname'],
        'status' =>$country['status'],
    ]);
}
?>